name: debug-pr-closed
on:
  pull_request:
    types: [closed]

jobs:
  test:
    if: ${{ github.event.pull_request.merged &&
            github.event.pull_request.base.ref == 'develop' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 PR #${{ github.event.number }} merged into develop"
